name: Generate GitHub Trophies

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  trophy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate trophy
        uses: Erik-Donath/github-profile-trophy@feature/generate-svg
        with:
          username: dridi10331
          file: trophy.svg
          token: ${{ secrets.GITHUB_TOKEN }}
          theme: tokyonight
          no-frame: true
          margin-width: 10

      - name: Commit trophy.svg
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update github trophy"
          file_pattern: trophy.svg
